name: wtfridge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  image_picker: ^1.1.2
  http: ^1.3.0
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.0
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
